# docker-compose.yml
version: '3.8'

services:
  # --- Serviço do Backend (API) ---
  backend:
    build:
      context: ./backend # Caminho para a pasta do backend
      dockerfile: backend.Dockerfile # Nome do Dockerfile do backend
    restart: always
    env_file:
      - ./.env.production # Aponta para o arquivo com as variáveis de ambiente
    networks:
      - recrutamento-net

  # --- Serviço do Frontend (React App) ---
  frontend:
    build:
      context: ./frontend # Caminho para a pasta do frontend
      dockerfile: frontend.Dockerfile # Nome do Dockerfile do frontend
    restart: always
    ports:
      # Mapeia a porta 80 do contêiner para a porta 80 do servidor
      - "80:80" 
    depends_on:
      - backend
    networks:
      - recrutamento-net

# --- Definição da Rede da Aplicação ---
# O Docker Compose criará esta rede para que os contêineres possam se comunicar
networks:
  recrutamento-net:
    driver: bridge