version: '3.8'

services:
  # Serviço do Backend
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    restart: always
    environment:
      - FRONTEND_URL=https://recrutamentoia.com.br
      - VITE_BASEROW_API_KEY=anGucsRrFCKrOmUYHapVYsr5U3FVK85o
      - GOOGLE_CLIENT_ID=726048519835-4o31uj1ssftc47a08kcb8hs1hkm2v040.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_REDIRECT_URI=https://backend.recrutamentoia.com.br/api/google/auth/callback
      - N8N_TRIAGEM_WEBHOOK_URL=https://webhook.focoserv.com.br/webhook/recrutamento
      - N8N_SCHEDULE_WEBHOOK_URL=https://webhook.focoserv.com.br/webhook/googleacesso
      - NODE_ENV=production
      - PORT=3001
    # O Docker vai criar e adicionar este serviço a uma rede padrão automaticamente.

  # Serviço do Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    # O Docker vai criar e adicionar este serviço à mesma rede padrão.

# A secção de redes foi removida. O Docker Compose vai tratar disto.