# docker-compose.yml
version: '3.8'

services:
  # Serviço do Backend
  backend:
    build:
      context: ./backend 
      dockerfile: backend.Dockerfile 
    restart: always
    env_file:
      - ./.env.production
    networks:
      - recrutamento-net

  # Serviço do Frontend
  frontend:
    build:
      context: ./frontend 
      dockerfile: frontend.Dockerfile 
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - recrutamento-net

# Definição da Rede da Aplicação
networks:
  recrutamento-net:
    driver: bridge